language: java

jdk:
  - openjdk11
  - oraclejdk13

# The trusty build environment allows for more memory, see https://docs.travis-ci.com/user/reference/overview/
dist: trusty

env:
  global:
    - MAVEN_OPTS="-Xmx6g"
  matrix:
    - TEST=org.matsim.run.**
    - TEST=org.matsim.episim.**

script:
  # Tests won't produce output immediately
  - travis_wait 30 mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e

# TODO: Add when everything was converted
#jobs:
#  include:
#    - stage: checkstyle
#      env: TEST=none
#      script: mvn checkstyle:check

cache:
  directories:
  - $HOME/.m2


